/** Editorial invitations, not claims of a calculated personal outcome. */
export const CHARACTER_QUESTIONS: Record<string, string> = {
  pungun: '버틸 힘은 있는데, 왜 같은 자리에서 다시 막힐까?',
  baegun: '더 노력하기 전에, 내게 먼저 필요한 조건은?',
  cheongam: '신중한 성격일까, 결정을 늦추는 습관일까?',
  sigye: '예전에는 통하던 방식이 지금도 통할까?',
  eunbyeol: '내가 아는 나와 사주가 읽는 나는 어디서 다를까?',
  jeokhyeol: '끌리는 마음과 감당할 수 있는 관계는 같을까?',
  monghwa: '새로운 것이 좋은 걸까, 지금을 벗어나고 싶은 걸까?',
  seoyeok: '남에게 좋은 선택이 나에게도 좋은 선택일까?',
  paeseon: '더 얻어야 풀릴까, 하나를 내려놓아야 풀릴까?',
  myeonsang: '밖에서는 괜찮은데 가까운 사람 앞에서는 왜 달라질까?',
  wolha: '가까워지고 싶은데, 왜 먼저 거리를 두게 될까?',
  hongmae: '관계를 지키려다 내가 원하는 조건을 놓친 건 아닐까?',
  yeondam: '다시 연락하고 싶은 마음에서, 내가 먼저 볼 것은?',
  hwagyeong: '말로 설명하는 나와 행동으로 드러나는 나는 같을까?',
  haengsu: '분명 열심히 버는데, 왜 내 몫은 남지 않을까?',
  hunjang: '아는 것이 많은데, 왜 시작 앞에서는 망설일까?',
  yakcho: '쉬고 있어도 마음이 일을 놓지 못하는 까닭은?',
  ilgwan: '상황은 바뀌었는데, 나는 같은 기준을 붙들고 있을까?',
  nopa: '오래 해온 선택이 지금의 나에게도 맞을까?',
  dongja: '답을 더 찾기 전에, 오늘은 무엇을 내려놓을까?',
};

/** Questions describe the existing chapter; they do not add new predictions. */
export const CHAPTER_QUESTIONS: Record<string, string> = {
  pungun_root: '흔들려도 돌아오는 힘, 내 사주에는 어디에 있을까?',
  pungun_wind: '내가 쓴 힘은 어디로 빠져나가고 있을까?',
  pungun_bowl: '지금 떠안은 몫은 내가 감당할 크기일까?',
  eunbyeol_gap: '유난히 잘하는 일 뒤에, 잘 쓰지 않는 힘은 무엇일까?',
  eunbyeol_scale: '내 안의 저울은 어느 쪽으로 기울어 있을까?',
  eunbyeol_silent: '익숙하지 않은 방식에 오히려 단서가 있을까?',
  seoyeok_sky: '다른 기준으로 읽으면 나는 어떻게 보일까?',
  seoyeok_cross: '두 가지 해석이 함께 가리키는 곳은 어디일까?',
  seoyeok_road: '먼 곳을 향하는 선택은 내 사주에서 어떻게 읽힐까?',
  hongmae_gwanjae: '책임을 떠안는 만큼 내 몫도 챙기고 있을까?',
  hongmae_tie: '내 곁에 두는 사람과 내가 기대하는 관계는 같을까?',
  hongmae_pick: '사람을 고를 때 나는 어떤 기준에 먼저 끌릴까?',
  baegun_johu: '지금 나에게 필요한 것은 속도일까, 여유일까?',
  baegun_seupjo: '내 기운의 균형은 어느 쪽으로 기울어 있을까?',
  baegun_cure: '더 채울 것과 덜어낼 것은 어떻게 다를까?',
  cheongam_gyeok: '여러 재주 중 내 명식의 중심에 놓인 것은?',
  cheongam_paint: '내 성향을 한 장면으로 그리면 무엇이 보일까?',
  cheongam_bone: '선택이 바뀌어도 남는 내 성향의 뼈대는?',
  sigye_now: '나는 지금 어떤 흐름의 한가운데에 있을까?',
  sigye_next: '다음 십 년은 지금과 무엇이 다르게 읽힐까?',
  sigye_missing: '태어난 시각을 알 때만 읽을 수 있는 것은?',
  monghwa_dream: '자꾸 마음에 남는 이미지, 사주에서는 무엇과 이어질까?',
  monghwa_beside: '가까운 관계에 붙은 옛 이름은 어떤 뜻일까?',
  monghwa_gate: '새로운 곳으로 향하는 마음은 어떻게 읽힐까?',
  wolha_seat: '가까운 사람 앞에서 드러나는 내 모습은?',
  wolha_thread: '내 사주에서 관계를 잇는 실마리는 무엇일까?',
  wolha_far: '거리를 두는 관계와 가까이 두는 관계는 어떻게 다를까?',
  hwagyeong_mirror: '내가 보는 나와 명식에 비친 나는 같을까?',
  hwagyeong_seat: '가까운 관계에서 유독 달라지는 모습은?',
  hwagyeong_edge: '나도 모르게 한쪽으로 기우는 힘은 무엇일까?',
  myeonsang_palace: '각 자리에 놓인 글자는 내 삶의 무엇을 비출까?',
  myeonsang_line: '윗대의 자리에서 읽는 내 성향의 단서는?',
  myeonsang_now: '지금의 흐름은 나를 어떻게 드러내게 할까?',
  nopa_floor: '버텨온 방식에서 여전히 나를 받쳐주는 것은?',
  nopa_time: '지금은 내 흐름의 어느 대목일까?',
  nopa_room: '내가 떠안을 수 있는 몫은 어떻게 읽힐까?',
  hunjang_seat: '내 재주는 어떤 방식으로 쓸 때 드러날까?',
  hunjang_lesson: '어릴 때 익힌 방식은 지금도 나를 돕고 있을까?',
  hunjang_turn: '다음 흐름에서는 어떤 힘을 먼저 보게 될까?',
  haengsu_flow: '애쓴 힘이 내 몫으로 돌아오는 흐름일까?',
  haengsu_hold: '버는 것과 쥐고 있는 것, 내 사주에서는 어떻게 다를까?',
  haengsu_book: '때가 바뀌면 돈을 읽는 관점도 달라질까?',
  ilgwan_term: '태어난 절기의 경계가 내 명식에 남긴 것은?',
  ilgwan_count: '내 명식의 해석을 가르는 계산의 기준은?',
  ilgwan_map: '내 대운의 시작과 경계는 어떻게 정해졌을까?',
  yakcho_lean: '한쪽으로 쏠린 생활을 돌아볼 단서는 무엇일까?',
  yakcho_fill: '나에게 부족한 여유는 어떤 관점으로 읽힐까?',
  yakcho_pace: '내 속도를 다시 살펴볼 자리는 어디일까?',
  yeondam_trace: '관계를 돌아볼 때 내 글자에서 먼저 볼 것은?',
  yeondam_lack: '사람에게서 채우려 했던 내 몫은 무엇일까?',
  yeondam_ask: '지금 묻는 관계는 내 명식의 어디와 이어질까?',
  jeokhyeol_spin: '내 마음이 강하게 쏠리는 쪽은 어떻게 읽힐까?',
  jeokhyeol_ask: '이 고민에 유독 힘을 쓰는 이유는 무엇일까?',
  jeokhyeol_ask2: '끌리는 대로 움직일 때 함께 살펴야 할 것은?',
  paeseon_wait: '내가 쥐지 못한 패는 무엇으로 읽힐까?',
  paeseon_ask: '지금의 고민에서 비어 있는 자리는 어디일까?',
  paeseon_ask2: '하나를 더 살핀다면 어떤 단서를 보게 될까?',
};
